---
kind: pipeline
type: kubernetes
name: build-tmsu

metadata:
  namespace: drone

steps:
- name: docker build
  image: plugins/docker
  settings:
    registry: registry.sud0.com
    repo: registry.sud0.com/tmsu
    tags: latest
    insecure: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
dns_config:
  options:
    - name: ndots
      value: 1
