---
kind: pipeline
type: kubernetes
name: build-tmsu

metadata:
  namespace: drone

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.home.sud0.com
    repo: registry.home.sud0.com/tmsu
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
